### ISSUE TITLE
Add a Dockerfile

### ISSUE THREAD

**Issue by dustinlacewell-wk** [OlegZee/FsChat#16]
It would be super helpful if there was a Dockerfile for building and running SAFE-Chat. This is mostly a reminder that I should contribute that.

**Comment by OlegZee** [comment]
Thank you for input. That was in my head, together with idea to create a demo server on heroku or other service. I won't put my hands on this case then, so waiting for you PR.

**Comment by OlegZee** [comment]
@AndrewEgorov made a PR with dockerfile and travis integration
